// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/applications": {
            "get": {
                "description": "Talent get applications",
                "tags": [
                    "Talent"
                ],
                "summary": "Talent get applications",
                "responses": {}
            }
        },
        "/api/applications/{id}": {
            "get": {
                "description": "Talent get application by id",
                "tags": [
                    "Talent"
                ],
                "summary": "Talent get application by id",
                "responses": {}
            }
        },
        "/api/employer": {
            "get": {
                "description": "Get employer data",
                "tags": [
                    "Employer"
                ],
                "summary": "Get employer data",
                "responses": {}
            }
        },
        "/api/employer/applications": {
            "get": {
                "description": "Employer get applications",
                "tags": [
                    "Employer"
                ],
                "summary": "Employer get applications",
                "responses": {}
            }
        },
        "/api/employer/applications/{id}": {
            "put": {
                "description": "Employer update application status",
                "tags": [
                    "Employer"
                ],
                "summary": "Employer update application",
                "responses": {}
            }
        },
        "/api/employer/jobs": {
            "get": {
                "description": "Employer get jobs",
                "tags": [
                    "Employer"
                ],
                "summary": "Employer get jobs",
                "responses": {}
            }
        },
        "/api/employer/login": {
            "post": {
                "description": "Login employer",
                "tags": [
                    "Employer"
                ],
                "summary": "Login employer",
                "responses": {}
            }
        },
        "/api/employer/logout": {
            "post": {
                "description": "Get employer data",
                "tags": [
                    "Employer"
                ],
                "summary": "Logout employer",
                "responses": {}
            }
        },
        "/api/employer/register": {
            "post": {
                "description": "Register employer",
                "tags": [
                    "Employer"
                ],
                "summary": "Register employer",
                "responses": {}
            }
        },
        "/api/job": {
            "post": {
                "description": "Employer post new job",
                "tags": [
                    "Employer"
                ],
                "summary": "Employer post job",
                "responses": {}
            }
        },
        "/api/job/{job_id}/apply": {
            "post": {
                "description": "Apply job",
                "tags": [
                    "Talent"
                ],
                "summary": "Apply Job",
                "responses": {}
            }
        },
        "/api/jobs": {
            "get": {
                "description": "Get all jobs",
                "tags": [
                    "Talent"
                ],
                "summary": "Get all jobs",
                "responses": {}
            }
        },
        "/api/talent": {
            "get": {
                "description": "Get talent data",
                "tags": [
                    "Talent"
                ],
                "summary": "Get talent data",
                "responses": {}
            }
        },
        "/api/talent/login": {
            "post": {
                "description": "Login talent",
                "tags": [
                    "Talent"
                ],
                "summary": "Login talent",
                "responses": {}
            }
        },
        "/api/talent/logout": {
            "post": {
                "description": "Get talent data",
                "tags": [
                    "Talent"
                ],
                "summary": "Logout talent",
                "responses": {}
            }
        },
        "/api/talent/register": {
            "post": {
                "description": "Register talent",
                "tags": [
                    "Talent"
                ],
                "summary": "Register talent",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Job Portal API",
	Description:      "This is a simple job portal API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
